# Workspace Memory Configuration Example
# 
# This configuration enables workspace memory for team collaboration,
# project progress tracking, and shared context management.

# Global workspace memory settings
enabled: true
disable_default_memory: true  # Set to true for workspace-only mode

# Tool configurations
tools:
  search:
    name: "cipher_workspace_search"
    description: "Search workspace memory for team and project information including progress, bugs, and collaboration context."
    enabled: true
    similarity_threshold: 0.7
    max_results: 10
    timeout_ms: 15000
  
  store:
    name: "cipher_workspace_store"
    description: "Background tool that automatically stores team-related information including project progress, bugs, and collaboration context."
    enabled: true
    auto_extraction: true
    confidence_threshold: 0.6
    batch_processing: true
    skip_patterns:
      - "search_results"
      - "retrieved_content"
      - "tool_output"
      - "system_message"

# Behavior configuration for automatic detection and extraction
behavior:
  search_triggers:
    keywords:
      - "team"
      - "project"
      - "progress"
      - "feature"
      - "bug"
      - "issue"
      - "collaborate"
      - "working on"
      - "assigned to"
      - "status"
      - "milestone"
      - "deadline"
      - "repository"
      - "branch"
    
    patterns:
      - "who.*working.*on"
      - "what.*status.*of"
      - "progress.*on.*feature"
      - "bugs.*in.*project"
      - "team.*member.*assigned"
      - "repository.*branch"
      - "current.*milestone"
    
    semantic_triggers:
      - "asking about team member activities"
      - "inquiring about project status"
      - "requesting progress updates"
      - "looking for bug reports"
      - "checking collaboration history"
  
  store_triggers:
    keywords:
      - "completed"
      - "working on"
      - "implemented"
      - "fixed"
      - "bug"
      - "issue"
      - "feature"
      - "milestone"
      - "deployed"
      - "released"
      - "blocked"
      - "reviewing"
      - "testing"
      - "merged"
      - "committed"
    
    patterns:
      - ".*completed.*feature"
      - ".*working.*on.*task"
      - ".*fixed.*bug"
      - ".*implemented.*component"
      - ".*deployed.*to.*environment"
      - ".*merged.*pull.*request"
      - ".*created.*branch"
      - ".*assigned.*to.*team"
    
    semantic_triggers:
      - "reporting progress on tasks"
      - "documenting bug fixes"
      - "sharing feature implementations"
      - "updating project status"
      - "recording team assignments"
  
  # Field extraction rules for automatic information parsing
  field_extraction:
    team_member:
      patterns:
        - "(?:worked on by|assigned to|developer|dev|team member)\\s+([a-zA-Z]+(?:\\s+[a-zA-Z]+)?)"
        - "(@[a-zA-Z_]+)"
        - "([A-Z][a-z]+(?:\\s+[A-Z][a-z]+)?)\\s+(?:is working on|completed|fixed|implemented)"
      required: false
    
    project_context:
      patterns:
        - "(?:project|app|application):\\s*([a-zA-Z0-9_-]+)"
        - "(?:in|for|on)\\s+(?:the\\s+)?([a-zA-Z0-9_-]+)\\s+project"
        - "(?:repo|repository):\\s*([a-zA-Z0-9_/-]+)"
        - "(?:branch|git checkout)\\s+([a-zA-Z0-9_/-]+)"
      required: false
    
    progress_status:
      patterns:
        - "(?:working on|implementing|developing|building)\\s+([^.!?]+)"
        - "(?:completed|done|finished|deployed|released)\\b"
        - "(?:blocked|stuck|waiting|pending)\\b"
        - "(?:reviewing|review|testing|qa)\\b"
      required: false
    
    bug_tracking:
      patterns:
        - "(?:bug|issue|error|problem):\\s*([^.!?]+)"
        - "(?:fixed|resolved|closed)\\s+(?:bug|issue|error):\\s*([^.!?]+)"
        - "(?:critical|high|medium|low)\\s+(?:priority|severity)"
      required: false

# Vector store configuration
vector_store:
  collection_name: "workspace_memory"
  similarity_threshold: 0.7
  max_results: 10
  rerank: false
  time_decay_factor: 0.1  # Optional: gives more weight to recent memories
  
  search_options:
    include_team_context: true
    include_project_context: true
    include_progress_info: true
    include_bug_reports: true
    filter_by_domain: false
    filter_by_team_member: false

# Embedding configuration
embedding:
  model: "text-embedding-3-small"
  dimension: 1536
  batch_size: 50
  timeout_ms: 30000
  
  preprocessing:
    preserve_team_mentions: true
    preserve_project_structure: true
    normalize_progress_terms: true
    extract_technical_context: true

# Performance optimization
performance:
  cache_enabled: true
  cache_ttl_seconds: 300  # 5 minutes
  batch_operations: true
  async_storage: true
  max_concurrent_operations: 3

# Error handling
error_handling:
  retry_attempts: 3
  retry_delay_ms: 1000
  fallback_to_heuristic: true
  log_extraction_failures: true